### ISSUE TITLE
Discussion: recommended to build sandbox first?

### ISSUE THREAD

**Issue by jonathanking** [prehensilecode/alphafold_singularity#10]
Thanks for providing this resource!

I found that just trying to run alphafold via singularity was very slow. Singularity would build a sandbox each time I ran the singularity image. I could get around this by using `singularity build --sandbox`, but I'm not sure if others have run into this issue as well. Do you have any recommendations? Or, am I making a mistake somewhere? Thanks for the help.

**Comment by prehensilecode** [comment]
`singularity build --sandbox` creates an image that is mutable. For distribution, the image should be immutable. From [`singularity-build(1)`](https://docs.sylabs.io/guides/3.5/user-guide/cli/singularity_build.html):

> It is a common workflow to use the "sandbox" mode for development of the container, and then build it as a default Singularity image for production use. The default format is immutable.

Feel free to create mutable images for your own use. I won't change the default behavior of building an immutable image.
