### ISSUE TITLE
openmm.patch file missing referenced by Singularity.def

### ISSUE THREAD

**Issue by amichaleas** [prehensilecode/alphafold_singularity#12]
# Apply OpenMM patch.
cd /opt/conda/lib/python3.7/site-packages
patch -p0 < /app/alphafold/docker/openmm.patch

Where can I acquire this openmm.patch file? 

Singularity Build Error:

/.post.script: 75: /.post.script: cannot open /app/alphafold/docker/openmm.patch: No such file
+ patch -p0
FATAL:   While performing build: while running engine: exit status 2

**Comment by prehensilecode** [comment]
It is in the AlphaFold source distribution, in the `docker` subdirectory: https://github.com/deepmind/alphafold/tree/main/docker

**Comment by prehensilecode** [comment]
> # Apply OpenMM patch.
> cd /opt/conda/lib/python3.7/site-packages patch -p0 < /app/alphafold/docker/openmm.patch
> 
> Where can I acquire this openmm.patch file?
> 
> Singularity Build Error:
> 
> /.post.script: 75: /.post.script: cannot open /app/alphafold/docker/openmm.patch: No such file
> 
> * patch -p0
>   FATAL:   While performing build: while running engine: exit status 2

You should not get this message if you have followed the instructions exactly. I.e. cloned this repo as a subdirectory of the alphafold directory from the alphafold repo.
