### ISSUE TITLE
Error for command "run": unknown flag: --env

### ISSUE THREAD

**Issue by infinity01** [prehensilecode/alphafold_singularity#16]
I am having issues using your Alphafold 2.2.4 singularity image on our slurm cluster.

After submitting the slurm script, I am receiving the below error:
        **Error for command "run": unknown flag: --env**

I see the run_singularity.py sets these options :

  options = [
    '--bind', f'{",".join(binds)}',
    '--env', 'TF_FORCE_UNIFIED_MEMORY=1',
    '--env', 'XLA_PYTHON_CLIENT_MEM_FRACTION=4.0',
    '--env', 'OPENMM_CPU_THREADS=12'
  ]

```
ALPHAFOLD_DIR=/shared/apps/alphafold
ALPHAFOLD_DATADIR=/shared/apps/alphafold-data/databases
FASTA_PATH=/home/user/Alphfold/emue_salk.fasta
I1216 09:40:09.914402 46912496419904 run_singularity.py:120] Binding /home/user/Alphfold -> /mnt/fasta_path_0
I1216 09:40:09.914582 46912496419904 run_singularity.py:120] Binding /shared/apps/alphafold-data/databases/uniref90 -> /mnt/uniref90_database_path
I1216 09:40:09.914649 46912496419904 run_singularity.py:120] Binding /shared/apps/alphafold-data/databases/mgnify -> /mnt/mgnify_database_path
I1216 09:40:09.914705 46912496419904 run_singularity.py:120] Binding /shared/apps/alphafold-data/databases -> /mnt/data_dir
I1216 09:40:09.914766 46912496419904 run_singularity.py:120] Binding /shared/apps/alphafold-data/databases/pdb_mmcif -> /mnt/template_mmcif_dir
I1216 09:40:09.914821 46912496419904 run_singularity.py:120] Binding /shared/apps/alphafold-data/databases/pdb_mmcif -> /mnt/obsolete_pdbs_path
I1216 09:40:09.914874 46912496419904 run_singularity.py:120] Binding /shared/apps/alphafold-data/databases/pdb70 -> /mnt/pdb70_database_path
I1216 09:40:09.914928 46912496419904 run_singularity.py:120] Binding /shared/apps/alphafold-data/databases/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I1216 09:40:09.914981 46912496419904 run_singularity.py:120] Binding /shared/apps/alphafold-data/databases/bfd -> /mnt/bfd_database_path
/shared/apps/alphafold/alphafold.sif
singularity run --nv --bind /home/user/Alphfold:/mnt/fasta_path_0,/shared/apps/alphafold-data/databases/uniref90:/mnt/uniref90_database_path,/shared/apps/alphafold-data/databases/mgnify:/mnt/mgnify_database_path,/shared/apps/alphafold-data/databases:/mnt/data_dir,/shared/apps/alphafold-data/databases/pdb_mmcif:/mnt/template_mmcif_dir,/shared/apps/alphafold-data/databases/pdb_mmcif:/mnt/obsolete_pdbs_path,/shared/apps/alphafold-data/databases/pdb70:/mnt/pdb70_database_path,/shared/apps/alphafold-data/databases/uniclust30/uniclust30_2018_08:/mnt/uniclust30_database_path,/shared/apps/alphafold-data/databases/bfd:/mnt/bfd_database_path,/tmp:/mnt/output --env TF_FORCE_UNIFIED_MEMORY=1 --env XLA_PYTHON_CLIENT_MEM_FRACTION=4.0 --env OPENMM_CPU_THREADS=12 /shared/apps/alphafold/alphafold.sif --fasta_paths=/mnt/fasta_path_0/emue_salk.fasta --uniref90_database_path=/mnt/uniref90_database_path/uniref90.fasta --mgnify_database_path=/mnt/mgnify_database_path/mgy_clusters_2018_12.fa --data_dir=/mnt/data_dir --template_mmcif_dir=/mnt/template_mmcif_dir/mmcif_files --obsolete_pdbs_path=/mnt/obsolete_pdbs_path/obsolete.dat --pdb70_database_path=/mnt/pdb70_database_path/pdb70 --uniclust30_database_path=/mnt/uniclust30_database_path/uniclust30_2018_08 --bfd_database_path=/mnt/bfd_database_path/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt --output_dir=/mnt/output --max_template_date=2020-05-14 --db_preset=full_dbs --model_preset=monomer --benchmark=False --use_precomputed_msas=False --num_multimer_predictions_per_model=5 --run_relax=True --use_gpu_relax=True --logtostderr
Error for command "run": unknown flag: --env
```

**Comment by infinity01** [comment]
It looks like the --env option was introduced in singularity 3.6
https://docs.sylabs.io/guides/3.7/user-guide/environment_and_metadata.html

The latest version our repository offers is 3.4
Any ideas on how to get this to work with 3.4?

**Comment by prehensilecode** [comment]
> It looks like the --env option was introduced in singularity 3.6 https://docs.sylabs.io/guides/3.7/user-guide/environment_and_metadata.html
> 
> The latest version our repository offers is 3.4 Any ideas on how to get this to work with 3.4?

Not sure. We only have Singularity (Sylabs) 3.8.7 on our cluster. Current Sylabs Singularity CE is 3.10.4. Apptainer "forked" (technically, it is Sylabs which forked) at Singularity  3.8.7.

Possible workarounds, neither of which I have tried:

1. Build the Singularity image after modifying the .def file to include the `%environment` with appropriate values, and deleting the `options` list from the `run_singularity.py` script. That would mean that your container image would be hardcoded with those environment variable values. IMO, this would have a good chance of working. However, building the container would require root privileges. Later versions of Singularity/Apptainer allow for building images without root privileges.
2. Build [Singularity](https://github.com/sylabs/singularity) or [Apptainer](https://github.com/apptainer) from source, creating a local install (i.e. not a package like .deb or .rpm). Running the AlphaFold container does not require SUID, I don't think.

**Comment by infinity01** [comment]
Thanks! i decided to just build 3.8.7 from source
