### ISSUE TITLE
Missing `uniclust30/uniclust30_2018_08`

### ISSUE THREAD

**Issue by GentleInfant** [prehensilecode/alphafold_singularity#19]
I've newly set up alphafold using your instructions for singularity (much more success than using Docker, thank you!). But when it comes to running `singularity/run_singularity.py` I'm getting an error about not being able to find `<data_dir>/uniclust30/uniclust30_2018_08`. I'm not sure but has it been renamed to `UniRef30` and the script needs to be updated?

**Comment by GentleInfant** [comment]
Created a PR that updates the reference https://github.com/prehensilecode/alphafold_singularity/pull/20

**Comment by prehensilecode** [comment]
The release version of `alphafold_singularity` is based on AlphaFold 2.2.4.

The [`README.md` of AlphaFold 2.2.4](https://github.com/deepmind/alphafold/blob/v2.2.4/README.md) shows that it downloads `uniclust30_2018_08`.

Please build the `alphafold_singularity` 2.2.4 with AlphaFold 2.2.4.

We'll plan for this change to go into version 2.3.1 to match AlphaFold 2.3.1, but it may be a few weeks before I get time to work on this.

**Comment by GentleInfant** [comment]
Ah, that would make sense. Well, you have this for when you're ready for it :)

**Comment by prehensilecode** [comment]
Addressed by 2d86f588fcdce82526397a0f1673edc492220662
