### ISSUE TITLE
prebuilt image missing

### ISSUE THREAD

**Issue by GentleInfant** [prehensilecode/alphafold_singularity#21]
While I'm here...

In your instructions you mention

> A prebuilt image is hosted on cloud.sylabs.io: https://cloud.sylabs.io/library/prehensilecode/alphafold_singularity/alphafold

However it appears not to exist

```bash
$ singularity pull library://prehensilecode/alphafold_singularity/alphafold
FATAL:   While pulling library image: error fetching image: image does not exist in the library: prehensilecode/alphafold_singularity/alphafold:latest (amd64)
```

Hitting the "Download" button on that page also has the timer just spinning for ever - no download ever starts.

**Comment by prehensilecode** [comment]
> While I'm here...
> 
> 
> 
> In your instructions you mention
> 
> 
> 
> > A prebuilt image is hosted on cloud.sylabs.io: https://cloud.sylabs.io/library/prehensilecode/alphafold_singularity/alphafold
> 
> 
> 
> However it appears not to exist
> 
> 
> 
> ```bash
> 
> $ singularity pull library://prehensilecode/alphafold_singularity/alphafold
> 
> FATAL:   While pulling library image: error fetching image: image does not exist in the library: prehensilecode/alphafold_singularity/alphafold:latest (amd64)
> 
> ```
> 
> 
> 
> Hitting the "Download" button on that page also has the timer just spinning for ever - no download ever starts.

Opening the link in a browser shows that it is there. Try a manual download. 

![image](https://user-images.githubusercontent.com/347755/216050669-6265a3f2-85e9-4157-b4fd-39571ca0c553.jpeg)

**Comment by prehensilecode** [comment]
Missed the last para. Please open issue with Sylabs: https://cloud.sylabs.io/support

**Comment by prehensilecode** [comment]
I tried the manual download, and it only began downloading after a delay of at least 10 minutes. When it did begin downloading, it took about 60 seconds.

My guess is that sylabs.io is throttling, and the delay means a `singularity pull` times out. So, my suggestion is to do a manual download of the `.sif` from the website.

**Comment by GentleInfant** [comment]
Sorry for not getting back earlier. Yeah I probably didn't wait 10 minutes. Thanks for looking into it further!
