### ISSUE TITLE
alphafold 2.3.2 could not locate params directory

### ISSUE THREAD

**Issue by artcmd** [prehensilecode/alphafold_singularity#33]
Hello! I tried the new version: alphafold_singularity 2.3.2-1 with AlphaFold 2.3.2.

``AlphaFold 2.3.2`` was cloned from [github.com/deepmind/alphafold/tree/v2.3.2](https://github.com/deepmind/alphafold/tree/v2.3.2).

``alphafold_2.3.2-1.sif`` was pulled from [cloud.sylabs.io/library/prehensilecode/alphafold_singularity/alphafold](https://cloud.sylabs.io/library/prehensilecode/alphafold_singularity/alphafold) and put in the directory ``alphafold-2.3.2/singularity``.

All the database files are located in ``alphafold_data``.

Here is my script:

```
module load singularity/3.8.3
module load cudatoolkit/11.7
export ALPHAFOLD_VERSION=2.3.2
cd ~/alphafold/alphafold-2.3.2
python singularity/run_singularity.py \
  --fasta_paths=P0DV34.fasta \
  --output_dir=~/monomer \
  --data_dir=~/alphafold_data \
  --max_template_date=2022-01-01 \
  --model_preset=monomer \
  --db_preset=full_dbs
```

The error message I got:
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 468, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/alphafold/run_alphafold.py", line 418, in main
    model_params = data.get_model_haiku_params(
  File "/app/alphafold/alphafold/model/data.py", line 30, in get_model_haiku_params
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data_dir/params/params_model_1.npz

**Comment by erdaqorri** [comment]
Hi! 
It seems like the params folder is not located in your Alphafold_data folder (which I assume contains all the databases). Check if the params dir is present in your alphafold_data folder, and if not move it there.

**Comment by prehensilecode** [comment]
@artcmd Please follow the instructions from AlphaFold for downloading the data needed to run AlphaFold: https://github.com/deepmind/alphafold i.e. using the `scripts/download_all_data.sh` script.
