### ISSUE TITLE
Relaxation step error CUDA_ERROR_ILLEGAL_ADDRESS

### ISSUE THREAD

**Issue by sarah872** [prehensilecode/alphafold_singularity#37]
Hi,
I opened an issue in the alphafold repo ([google-deepmind/alphafold/#581](https://github.com/google-deepmind/alphafold/issues/831)) because I'm running into an error in the relaxation step. 

This is the command I'm using:
```
run_alphafold_singularity.py --fasta-paths protein.fasta --output-dir ./norelax_2.3.2 --cpus=$SLURM_CPUS_PER_TASK --gpu-devices cuda:${CUDA_VISIBLE_DEVICES} --model-preset multimer --data-dir /scratch/mirror/alphafold/2.3.2 --db-preset full_dbs
```
and it seems that I am running alphafold without the relaxation (I did not set `--run-relax`), but still the error persists?

**Comment by prehensilecode** [comment]
Sorry, I am unable to assist in actually using AlphaFold.
