### ISSUE TITLE
Alphafold singularity error

### ISSUE THREAD

**Issue by sumitsaluja** [prehensilecode/alphafold_singularity#40]
I David,
I i build Alphafold singularity from your github code, now when users run singularity he is getting error. Any recommendations ?

![image](https://github.com/user-attachments/assets/715512f5-ef22-4556-8d69-da0256fd44a7)

**Comment by prehensilecode** [comment]
Try the pre-built image at https://cloud.sylabs.io/library/prehensilecode/alphafold_singularity/alphafold
