### ISSUE TITLE
update to 2.2.3?

### ISSUE THREAD

**Issue by ckywong** [prehensilecode/alphafold_singularity#6]
I just wonder if there will be an update to match alphafold version 2.2.3.  Thank you.

**Comment by prehensilecode** [comment]
> I just wonder if there will be an update to match alphafold version 2.2.3. Thank you.

Working on it. No timeline, I'm afraid. This project is not part of my regular sysadmin duties.

**Comment by ckywong** [comment]
Understand.  Thank you very much for spending time on it!

**Comment by prehensilecode** [comment]
Skipping 2.2.3 and going 2.2.4 (current release as of 2022-09-30). Should be out next week, and uploaded to Sylabs Cloud.

**Comment by prehensilecode** [comment]
[Version 2.2.4](https://github.com/prehensilecode/alphafold_singularity/releases/tag/v2.2.4) corresponding to [AlphaFold 2.2.4](https://github.com/deepmind/alphafold/releases/tag/v2.2.4) has been released. Image file has been [published on Sylabs Cloud](https://cloud.sylabs.io/library/prehensilecode/alphafold_singularity/alphafold). (There is only enough space there for one image to be hosted, so it will default to the latest.)
